name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Test with pytest
      run: |
        pip2 -V
        pip3 -V
    - name: Install Dependencies
      run: |
        pip2 install grpcio protobuf pyyaml gevent grpcio-tools
        pip3 install grpcio protobuf pyyaml
    - name: test docker
      run: |
        docker version
